### ISSUE TITLE
Implementasikan Revisi Maximum Profit(MP) seperti di dataset IBM(2) ke dataset (1) dan (3)

### ISSUE THREAD

**Issue by wijayadavin** [wijayadavin/employee_uplift#1]
### Output yang ingin direvisi **untuk** dataset(1) dan (3), antara lain:
Output **dari** bagian Create new dataframe for churn and uplift
![1](https://user-images.githubusercontent.com/33082426/76141724-a869f300-6099-11ea-96f5-09642f7adcfc.jpg)

### **hingga** sebelum pylift:
![2](https://user-images.githubusercontent.com/33082426/76141727-aacc4d00-6099-11ea-884d-36e31f4cc98c.jpg)

------------------------------------------------------------------------------------------------------
### Contoh Output yang **sudah benar**(seperti hasil dari dataset IBM):
![capture-20200307-172805](https://user-images.githubusercontent.com/33082426/76141679-25489d00-6099-11ea-9b62-72cf566d4478.jpg)
![capture-20200307-172839](https://user-images.githubusercontent.com/33082426/76141680-2aa5e780-6099-11ea-9324-efb18a3c4f08.jpg)

**Comment by habbeybds** [comment]
okay aku coba cek ya. sorry lama soalnya lagi banyak banget masalah dikantorku yang harus dikerjakan sampe ga tidur-tidur

**Comment by wijayadavin** [comment]
> okay aku coba cek ya. sorry lama soalnya lagi banyak banget masalah dikantorku yang harus dikerjakan sampe ga tidur-tidur

noted, thank you Jum

**Comment by wijayadavin** [comment]
thank you @habbeybds
